<template>
  <section class="container">
    <h1>Mon article</h1>
    <div class="content">
      <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse est ex ipsum, iste natus nisi quasi repellendus sit vero voluptatum. Adipisci commodi culpa, dignissimos esse in natus! Est, ipsum mollitia.</span><span>Eos, excepturi facilis fugiat ipsum libero maiores minus modi nisi nostrum odio recusandae sit. A doloremque molestiae quod vero? Architecto asperiores consequatur dolore dolores itaque iure magni neque quam voluptate?</span><span>Asperiores aspernatur, at cum enim eos fugit mollitia nam nemo nihil officia placeat quaerat qui recusandae repellendus sed. Beatae eveniet fugit harum ipsa itaque nemo nisi non sed tempora vitae.</span><span>A ad alias aliquid asperiores consectetur cumque debitis eligendi id neque, nesciunt porro quos unde vel voluptas, voluptates! Aspernatur assumenda culpa enim fuga inventore laboriosam magni nostrum pariatur perferendis praesentium?</span>
      </p>
      <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto, atque, culpa debitis dicta dolorem eaque error excepturi expedita hic iste iure magnam neque quas reiciendis saepe sint soluta velit voluptatem.</span><span>Nihil quae quasi quia! Ad aliquid aperiam, architecto atque autem commodi ea eligendi ex illo incidunt iste laudantium nihil non provident quam quod recusandae repudiandae ullam ut veniam veritatis vero.</span><span>Eligendi eveniet illo mollitia nobis odio quas quasi unde? A adipisci consequuntur corporis, ducimus eos natus nemo nesciunt nulla porro vitae. Maxime, officia, officiis. Ad autem molestiae nisi perferendis rem?</span><span>Aperiam aut cumque debitis deserunt earum excepturi facilis labore minima minus modi molestiae numquam officia omnis, pariatur quisquam ratione sit, tenetur vel! Cupiditate eos exercitationem expedita laboriosam molestiae pariatur voluptate.</span>
      </p>
      <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus adipisci animi asperiores consectetur cupiditate dignissimos ex facere in, iusto laudantium magni maxime nemo numquam omnis quos sequi, sit sunt voluptas!</span><span>Ab aliquid cum, deserunt dolores eveniet excepturi explicabo harum inventore laudantium nihil nobis nulla odio omnis perspiciatis quae quo suscipit unde! Amet distinctio dolorum, enim itaque libero neque officiis saepe.</span><span>Amet animi asperiores aut, dicta eaque fugit nam nesciunt numquam odio quaerat repellendus sapiente veniam? Alias aut, cum doloremque, dolorum inventore ipsa labore magnam placeat, reprehenderit saepe veniam voluptas voluptates.</span><span>Amet commodi fugiat nostrum perspiciatis placeat voluptate voluptatum! Accusamus animi blanditiis cumque doloribus esse ex expedita, explicabo facilis fuga ipsa laboriosam libero obcaecati quasi, qui quisquam ratione totam ullam vel!</span>
      </p>
      <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam assumenda dolor earum esse harum numquam porro, quis repudiandae tempore vel! Consectetur deserunt distinctio ea eos placeat quasi, quibusdam vero voluptates.</span><span>Commodi corporis culpa deleniti enim error, et fugit ipsum iure magni maiores minus, mollitia quia quidem sed suscipit. Adipisci dolore dolorum eos expedita id incidunt magni odit optio placeat sit!</span><span>Ea, eaque ipsum omnis recusandae rerum ullam. Adipisci amet commodi deleniti dolor in maiores maxime nesciunt nisi vitae, voluptatem. Dolor inventore laudantium molestias mollitia, nihil odio officia quidem sunt veniam!</span><span>Eaque, laboriosam, veritatis. Adipisci at beatae blanditiis debitis eligendi enim et, excepturi facilis iure molestiae natus neque nobis nostrum officia, possimus quas qui quidem quos rem rerum sit vel voluptates?</span>
      </p>
      <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id magnam mollitia omnis ullam velit. Consequuntur corporis dicta ex iusto nulla reprehenderit similique vitae voluptas! Assumenda eos in nesciunt quae tenetur.</span><span>Accusantium adipisci blanditiis debitis, dignissimos distinctio dolore eaque eius eligendi error explicabo facere illo in, maxime modi nam odio quibusdam quidem recusandae reiciendis reprehenderit sequi ullam velit voluptates! Hic, voluptas.</span><span>Cupiditate deserunt dolor ducimus error ex exercitationem ipsam, magnam minus nam nesciunt nostrum nulla numquam qui rem sapiente voluptas voluptatibus, voluptatum. Asperiores dolorum incidunt iure obcaecati placeat sunt, voluptatem? Maiores.</span><span>Aliquam atque deleniti harum in molestias, repellat similique veniam. Accusantium adipisci, consequatur consequuntur debitis delectus distinctio dolor eum, impedit mollitia nihil nisi numquam obcaecati odit officiis praesentium, reprehenderit voluptas. Consequatur!</span>
      </p>
      <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores blanditiis iste molestias sit. Alias cupiditate dolorum ducimus error eveniet ex excepturi expedita inventore molestias, mollitia perferendis porro quaerat quasi quia.</span><span>Atque dicta earum omnis repudiandae. Amet earum excepturi libero minima porro sapiente similique tempore, unde vitae voluptatum! Ducimus eius error ipsam laboriosam nihil provident quibusdam, saepe sequi, sint unde ut!</span><span>Ad aspernatur, commodi consectetur dolorem ea est eum facere facilis harum illo incidunt iste laboriosam minima molestias nisi nostrum porro qui saepe sed sunt, tenetur ullam unde ut voluptas, voluptatum?</span><span>Asperiores blanditiis cumque eaque est eum hic ipsam quis quisquam soluta tempore. Consequatur illo iste numquam omnis perspiciatis quae quis rem repellendus vitae! Consectetur cupiditate in perferendis porro rem reprehenderit.</span>
      </p>
      <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto consequatur culpa enim eum ex expedita fugit minus natus nostrum officia pariatur perferendis quas quo repellat repudiandae, similique tempore voluptate voluptatem?</span><span>Asperiores aut consectetur consequuntur distinctio eum expedita explicabo facere, facilis in itaque laboriosam magnam nemo nihil nostrum quasi quibusdam repellat tempora ut. Consequuntur nostrum quis quo sint voluptas. Nostrum, repudiandae!</span><span>Accusamus commodi, doloribus eligendi enim esse est eum exercitationem explicabo fugiat id ipsam iste iure iusto non odio perferendis quaerat qui quia quidem recusandae reiciendis repudiandae soluta totam vel velit?</span><span>Alias eaque earum eum fugit, magni modi velit voluptas? Deleniti doloribus earum excepturi voluptatum! Ad, autem, cum cumque eum eveniet ex exercitationem laudantium nihil nobis, quam similique sit tempore voluptate.</span>
      </p>
      <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dicta eius eum exercitationem harum illum incidunt maiores necessitatibus nisi nulla pariatur, possimus qui rerum sed, suscipit temporibus tenetur velit voluptas.</span><span>Ab alias aperiam assumenda debitis dolor enim facilis laborum laudantium nemo nostrum possimus quis quod recusandae sint, suscipit! Aperiam, at atque dolores libero molestias mollitia odit officia quia reprehenderit sint.</span><span>Culpa, quis, voluptate. Accusamus adipisci alias aliquam animi beatae corporis doloremque expedita impedit ipsa ipsum iste labore neque nesciunt odit praesentium quas, quis reiciendis reprehenderit sed tempore vel veniam voluptates.</span><span>Commodi illo iusto perferendis totam. Accusantium ad animi architecto asperiores atque autem, beatae blanditiis dolores doloribus expedita molestiae nemo nulla optio pariatur praesentium qui ratione similique soluta tempore ullam ut.</span>
      </p>
      <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium adipisci amet asperiores aut blanditiis deserunt et id nostrum odit, omnis quaerat, quam quidem ratione reprehenderit rerum similique sit ullam vitae.</span><span>Blanditiis dolore, earum et facere, fugit, hic laboriosam magni nihil quas quis quisquam reprehenderit suscipit tenetur vel voluptatum. Assumenda cupiditate distinctio dolorem expedita ipsam magnam minima mollitia, quam quia sequi.</span><span>Alias aperiam dolore enim eos error esse explicabo incidunt, iste, maxime molestias, nam natus neque odit officiis omnis perferendis provident repellat saepe sapiente similique tempore temporibus totam veniam vero voluptatum?</span><span>Alias consectetur cumque dolor dolores ea esse harum in itaque maiores minima natus pariatur possimus, sequi vel voluptas voluptatem voluptatum? Accusantium eaque eveniet exercitationem harum quod rem reprehenderit, sequi voluptates?</span>
      </p>
      <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste placeat ratione recusandae, sed sit voluptatem. A asperiores aut dignissimos esse ex ipsum minima odit, quasi qui rem sed ut voluptatem.</span><span>Ab distinctio enim facere quas quasi sed similique voluptas voluptates voluptatum. Amet delectus, dolor dolore dolorum expedita fuga ipsa non officia optio, perferendis qui quibusdam quod repellat saepe sed soluta!</span><span>Accusamus cum dolor doloremque dolores ea eius ipsam ipsum iure iusto minus, mollitia obcaecati pariatur perspiciatis quia rem sequi suscipit? A earum explicabo illo modi non, similique sunt. Commodi, incidunt.</span><span>Accusantium ad commodi earum et expedita magnam nemo quaerat quisquam tempora voluptatibus! Aliquam assumenda enim eos et explicabo harum itaque, labore laboriosam maiores placeat quibusdam quis quod rem sed voluptatibus?</span>
      </p>
    </div>
  </section>
</template>

<script>
  export default {}
</script>

<style>
  .container {
    min-height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    text-align: center;
    flex-direction: column;
  }
</style>
